package entities;
// Generated Aug 3, 2022 1:23:10 AM by Hibernate Tools 4.3.1



/**
 * Item generated by hbm2java
 */
public class Item  implements java.io.Serializable {


     private int id;
     private String iname;
     private Integer price;
     private String description;
     private String available;

    public Item() {
    }

	
    public Item(int id) {
        this.id = id;
    }
    public Item(int id, String iname, Integer price, String description, String available) {
       this.id = id;
       this.iname = iname;
       this.price = price;
       this.description = description;
       this.available = available;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getIname() {
        return this.iname;
    }
    
    public void setIname(String iname) {
        this.iname = iname;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getAvailable() {
        return this.available;
    }
    
    public void setAvailable(String available) {
        this.available = available;
    }




}


