package entities;
// Generated Aug 3, 2022 1:23:10 AM by Hibernate Tools 4.3.1



/**
 * OrderHistory generated by hbm2java
 */
public class OrderHistory  implements java.io.Serializable {


     private Integer id;
     private byte[] bill;
     private String path;

    public OrderHistory() {
    }

    public OrderHistory(byte[] bill, String path) {
       this.bill = bill;
       this.path = path;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public byte[] getBill() {
        return this.bill;
    }
    
    public void setBill(byte[] bill) {
        this.bill = bill;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }




}


