package entities;
// Generated Aug 3, 2022 1:23:10 AM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String email;
     private String address;
     private String gender;
     private Integer contactNo;

    public User() {
    }

    public User(String name, String email, String address, String gender, Integer contactNo) {
       this.name = name;
       this.email = email;
       this.address = address;
       this.gender = gender;
       this.contactNo = contactNo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Integer getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(Integer contactNo) {
        this.contactNo = contactNo;
    }




}


